# Generated by Django 5.0 on 2026-09-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_logo_education_website_alter_education_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='experience',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
