# Generated by Django 5.0 on 2026-09-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
