# Generated by Django 5.0 on 2026-09-16 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('academic', 'Academic'), ('competition', 'Competition'), ('certification', 'Certification'), ('award', 'Award'), ('other', 'Other')], max_length=20, null=True)),
                ('achievements_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
