# Generated by Django 5.0 on 2026-09-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_achievements_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='achievements_image_url',
        ),
    ]
