# Generated by Django 5.0 on 2026-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_achievements_achievements_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='achievements_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
