# Generated by Django 5.0 on 2026-09-21 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_achievements_achievements_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
