# Generated by Django 5.0 on 2026-10-05 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_achievements_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'academic'), ('Competition', 'competition'), ('Certification', 'certification'), ('Award', 'award'), ('Other', 'other')], max_length=20, null=True),
        ),
    ]
